import { Inter, Poppins, Roboto } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets:["latin"],
  weight:['400','700','100']
});
const poppins = Poppins({subsets:["latin"],weight:['400','700','100','200','300','500','800','900']});

export const metadata = {
  title: "NoteHarbor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
